# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
trigger:
  - main
pr:
  - main

variables:
  GO_VERSION: 1.16
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: Checks
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make checks
        displayName: Run checks

  - job: UnitTest
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make unit-test
        displayName: Run unit test
      - script: bash <(curl https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN
        env:
          CODECOV_UPLOAD_TOKEN: $(CODECOV_UPLOAD_TOKEN)
        displayName: Upload coverage to Codecov

  - job: BDDTest
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          echo '127.0.0.1 testnet.trustbloc.local' | sudo tee -a /etc/hosts
          echo '127.0.0.1 stakeholder.one' | sudo tee -a /etc/hosts
          echo '127.0.0.1 stakeholder.two' | sudo tee -a /etc/hosts
          echo '127.0.0.1 sidetree-mock' | sudo tee -a /etc/hosts
          make bdd-test
        displayName: Run BDD tests

  - job: Publish
    dependsOn:
      - Checks
      - UnitTest
      - BDDTest
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          function logout {
            docker logout
          }
          trap logout EXIT
          source ci/version_var.sh
          echo $DOCKER_PASSWORD | docker login ghcr.io --username $DOCKER_USER --password-stdin
          make did-method-rest-docker
          docker tag ghcr.io/trustbloc/driver-did-trustbloc:latest ${TRUSTBLOC_DID_METHOD_PKG}:${TRUSTBLOC_DID_METHOD_TAG}
          docker push ${TRUSTBLOC_DID_METHOD_PKG}:${TRUSTBLOC_DID_METHOD_TAG}
          make did-method-cli-docker
          docker tag ghcr.io/trustbloc/did-method-cli:latest ${TRUSTBLOC_DID_METHOD_CLI_PKG}:${TRUSTBLOC_DID_METHOD_TAG}
          docker push ${TRUSTBLOC_DID_METHOD_CLI_PKG}:${TRUSTBLOC_DID_METHOD_TAG}
        env:
          DOCKER_USER: $(DOCKER_USER)
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
